### PR TITLE
Add support for localized dates

### PR DESCRIPTION
**Pull request by aurelien31**
Hi,

I am proposing this PR to allow support for localized dates, bceause depending on the language, the dates are not written in the same way (eg: "September 8, 2020" in French gives "8 septembre 2020").

Since the used package modifies the locale automatically, it's quite easy to transform the dates without much modification.

This PR brings 2 changes since it allows the date to be translated into the chosen language and also to apply the correct format.

After research, I also applied the localized date format to the other languages ​​currently available (to be checked by their authors perhaps to be sure : @olsza, @danrcastro, @wilsenhc).

Regards...

### CODE REVIEW

**Comment by wilsenhc** [comment]
Just tested it for Spanish and it looks all good to me

**Comment by danrcastro** [comment]
Portuguese looks good as well

**Comment by mattstauffer** [comment]
Thank you so much!!

**Comment by olsza** [comment]
cool, thanks @aurelien31

**Pull request merged**
